{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 12}, "tests": {"0": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_7z_a", "rerun": "0"}, "1": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_7z_e", "rerun": "0"}, "2": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_7z_t", "rerun": "0"}, "3": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_7z_d", "rerun": "0"}, "4": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_7z_u", "rerun": "0"}, "5": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_file_exist", "rerun": "0"}, "6": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_extract_file_compare_7z_e", "rerun": "0"}, "7": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_crc32", "rerun": "0"}, "8": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_7z_x", "rerun": "0"}, "9": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_7z_l", "rerun": "0"}, "10": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_extract_broken", "rerun": "0"}, "11": {"status": "ERROR", "message": "load_config_yml = {'arch_name': 'arch', 'archive_type': 'zip', 'bs': 11024, 'count': 5, ...}\n\n    @pytest.fixture(scope='function', autouse=True)\n    def write_stat(load_config_yml):\n>       with open('/proc/loadvg' 'r') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/proc/loadvgr'\n\nconftest.py:63: FileNotFoundError\n", "test_name": "test_test_broken", "rerun": "0"}}, "suite_name": "tests/test_1.py"}}}, "date": "August 12, 2024", "start_time": 1723410441.3301268, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "12", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "12"}